# Generated by Django 4.1 on 2022-09-25 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='seen_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.TimeField(default=django.utils.timezone.now)),
                ('seen', models.BooleanField(default=False)),
                ('studnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='session_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.TextField()),
                ('session', models.FileField(upload_to='')),
                ('akhtbar', models.ManyToManyField(to='auth_app.akhtbar')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seen_db', models.ManyToManyField(to='mohdrate_DB.seen_db')),
            ],
        ),
        migrations.CreateModel(
            name='scientific_material_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('scientific_material_name', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seen', models.ManyToManyField(to='mohdrate_DB.seen_db')),
                ('session', models.ManyToManyField(to='mohdrate_DB.session_db')),
            ],
        ),
    ]
