# Generated by Django 4.1 on 2022-09-25 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mohdrate_DB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_db',
            name='time_zone',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session_db',
            name='seen_db',
            field=models.ManyToManyField(blank=True, null=True, to='mohdrate_DB.seen_db'),
        ),
    ]
