# Generated by Django 4.1 on 2022-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohdrate_DB', '0003_alter_session_db_akhtbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientific_material_db',
            name='seen',
            field=models.ManyToManyField(blank=True, null=True, to='mohdrate_DB.seen_db'),
        ),
        migrations.AlterField(
            model_name='scientific_material_db',
            name='session',
            field=models.ManyToManyField(blank=True, null=True, to='mohdrate_DB.session_db'),
        ),
    ]
