# Generated by Django 4.1 on 2022-09-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohdrate_DB', '0004_alter_scientific_material_db_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientific_material_db',
            name='session',
            field=models.ManyToManyField(to='mohdrate_DB.session_db'),
        ),
    ]
