# Generated by Django 4.1 on 2022-09-25 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='akhtbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so2al', models.TextField()),
                ('akhtbar_name', models.TextField(default='name')),
                ('agaba1', models.TextField(blank=True, null=True)),
                ('agaba2', models.TextField(blank=True, null=True)),
                ('agaba3', models.TextField(blank=True, null=True)),
                ('als7', models.TextField(blank=True, null=True)),
                ('rate', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='prof_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('akhtbar', models.ManyToManyField(to='auth_app.akhtbar')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
