# Generated by Django 4.1 on 2022-09-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akhtbar',
            name='agaba1',
        ),
        migrations.RemoveField(
            model_name='akhtbar',
            name='agaba2',
        ),
        migrations.RemoveField(
            model_name='akhtbar',
            name='agaba3',
        ),
        migrations.RemoveField(
            model_name='akhtbar',
            name='als7',
        ),
    ]
