# Generated by Django 4.1 on 2022-09-27 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0002_remove_akhtbar_agaba1_remove_akhtbar_agaba2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ansers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akhtbar_name', models.TextField(default='ادخل الاجابه هنا')),
                ('asner', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='akhtbar',
            name='anserrelated',
            field=models.ManyToManyField(to='auth_app.ansers'),
        ),
    ]
